package com.dolan.namruev.kemal.word_bot.model;

public enum ConstructorDocState {
    STATE_START,
    ASK_COURT_NAME,
    ASK_COURT_ADDRESS,
    ASK_APPLICANT_NAME,
    ASK_APPLICANT_ADDRESS,
    ASK_INN_APPLICANT,
    ASK_DEFENDANT_NAME,
    ASK_DEFENDANT_ADDRESS,
    ASK_INN_DEFENDANT,
    ASK_CASE_NUMBER,
    ASK_DATE_COURT,
    ASK_TIME_COURT,
    ASK_REASON_ONE,
    COMPLETE,
    WAITING_OPTION,
    STATE_CANCELLED
}
